// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0ZTCbwsiY_78Bh8npbN1SfvB2_P4Bh4',
    appId: '1:555977304287:web:a667e3c92f771c8717e16a',
    messagingSenderId: '555977304287',
    projectId: 'donnor-s-choice-67b7d',
    authDomain: 'donnor-s-choice-67b7d.firebaseapp.com',
    storageBucket: 'donnor-s-choice-67b7d.appspot.com',
    measurementId: 'G-49CGDJHC74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDClLp3OW6ssMM97POs4_akC4aOS9wVAPQ',
    appId: '1:555977304287:android:d4c06d9a32598eb317e16a',
    messagingSenderId: '555977304287',
    projectId: 'donnor-s-choice-67b7d',
    storageBucket: 'donnor-s-choice-67b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAYMec4c2SWnq6xMlmS2a6V2-CZvSzKE',
    appId: '1:555977304287:ios:e7217d903dc4cf3117e16a',
    messagingSenderId: '555977304287',
    projectId: 'donnor-s-choice-67b7d',
    storageBucket: 'donnor-s-choice-67b7d.appspot.com',
    iosClientId:
        '555977304287-kue97f292uieeotavam1374ao8aak804.apps.googleusercontent.com',
    iosBundleId: 'com.example.donnorsChoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAYMec4c2SWnq6xMlmS2a6V2-CZvSzKE',
    appId: '1:555977304287:ios:e7217d903dc4cf3117e16a',
    messagingSenderId: '555977304287',
    projectId: 'donnor-s-choice-67b7d',
    storageBucket: 'donnor-s-choice-67b7d.appspot.com',
    iosClientId:
        '555977304287-kue97f292uieeotavam1374ao8aak804.apps.googleusercontent.com',
    iosBundleId: 'com.example.donnorsChoice',
  );
}
